---
- include:        tasks/distro.yml

- name:           Docker | Add Docker GPG key
  apt_key:        url=https://download.docker.com/linux/ubuntu/gpg

- name:           Docker | Add Docker APT repository
  apt_repository:
    repo:         deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name:           Docker | Install Docker
  apt:
    name:         ['docker-ce']
    state:        present

- name:           Docker | Start Docker
  service:
    name:         docker
    state:        started
